namespace StandardTestNext.Contracts;

public sealed class TestRecordQuerySeedContract
{
    public MotorRatedParamsContract RatedParams { get; init; } = new();
    public IReadOnlyList<MotorRealtimeSampleContract> Samples { get; init; } = Array.Empty<MotorRealtimeSampleContract>();
    public IReadOnlyList<LegacyMotorRealtimeEnvelopeContract> LegacySamples { get; init; } = Array.Empty<LegacyMotorRealtimeEnvelopeContract>();
    public int NoLoadRConverseType { get; init; }
}

public static class TestRecordQuerySeedFactory
{
    public static TestRecordQuerySeedContract CreateDefault()
    {
        var now = DateTimeOffset.Now;
        var rated = new MotorRatedParamsContract
        {
            ProductKind = "Motor_Y",
            Model = "Y-160M-4",
            StandardCode = "GB1032-2023",
            RatedPower = 11,
            RatedCurrent = 22.4,
            RatedVoltage = 380,
            RatedSpeed = 1470,
            RatedFrequency = 50,
            Pole = 4,
            PolePairs = 2,
            Duty = "S1",
            InsulationGrade = "F",
            PowerFactor = 0.86,
            Weight = 95,
            IngressProtection = "IP55",
            Connection = "Delta"
        };

        var legacySamples = new[]
        {
            new LegacyMotorRealtimeEnvelopeContract
            {
                SampleTime = now,
                DeviceId = "legacy-app-query-seed-01",
                ProductKind = rated.ProductKind,
                VoltageAverage = 380.1,
                CurrentAverage = 21.6,
                Power = 10.4,
                Frequency = 50,
                Speed = 1472,
                Torque = 68.1,
                IsRecordPoint = true,
                Uab = 381.2,
                Ubc = 379.8,
                Uca = 379.3,
                Uavg = 380.1,
                Ia = 21.2,
                Ib = 21.8,
                Ic = 21.7,
                Iavg = 21.6,
                CosPhi = 0.86,
                DeltaI = 0.6,
                AccX1 = 0.12,
                AccY1 = 0.08,
                AccZ1 = 0.05,
                VelX1 = 1.2,
                VelY1 = 1.1,
                VelZ1 = 1.0,
                DisX1 = 0.02,
                DisY1 = 0.03,
                DisZ1 = 0.01,
                AccX2 = 0.10,
                AccY2 = 0.09,
                AccZ2 = 0.04,
                VelX2 = 1.0,
                VelY2 = 0.9,
                VelZ2 = 0.8,
                DisX2 = 0.03,
                DisY2 = 0.02,
                DisZ2 = 0.01,
                Temp1 = 68.2,
                Temp2 = 69.1,
                Temp3 = 67.8,
                Temp4 = 68.5,
                Temp5 = 41.3,
                Temp6 = 40.9,
                Temp7 = 39.8,
                Temp8 = 38.7,
                AmbientHumidity = 62.4,
                AmbientTemperature = 24.8,
                UabIncoming = 381.4,
                UbcIncoming = 380.1,
                UcaIncoming = 379.6,
                UavgIncoming = 380.4,
                IaIncoming = 22.0,
                IbIncoming = 21.9,
                IcIncoming = 22.1,
                IavgIncoming = 22.0,
                PIncoming = 10.9,
                FrequencyIncoming = 50,
                LeaveFactoryModePowerCurveImage = "curve://leave-factory/power/1",
                LeaveFactoryModeTempCurveImage = "curve://leave-factory/temp/1",
                TempRiseModePowerCurveImage = "curve://temp-rise/power/1",
                TempRiseModeTempCurveImage = "curve://temp-rise/temp/1"
            },
            new LegacyMotorRealtimeEnvelopeContract
            {
                SampleTime = now.AddSeconds(1),
                DeviceId = "legacy-app-query-seed-01",
                ProductKind = rated.ProductKind,
                VoltageAverage = 379.8,
                CurrentAverage = 21.8,
                Power = 10.5,
                Frequency = 50,
                Speed = 1471,
                Torque = 68.7,
                IsRecordPoint = false,
                Uab = 380.0,
                Ubc = 379.7,
                Uca = 379.8,
                Uavg = 379.8,
                Ia = 21.6,
                Ib = 21.9,
                Ic = 21.8,
                Iavg = 21.8,
                CosPhi = 0.87,
                DeltaI = 0.3,
                AccX1 = 0.11,
                AccY1 = 0.07,
                AccZ1 = 0.05,
                VelX1 = 1.3,
                VelY1 = 1.0,
                VelZ1 = 1.0,
                DisX1 = 0.02,
                DisY1 = 0.02,
                DisZ1 = 0.01,
                AccX2 = 0.10,
                AccY2 = 0.08,
                AccZ2 = 0.04,
                VelX2 = 1.0,
                VelY2 = 0.9,
                VelZ2 = 0.8,
                DisX2 = 0.03,
                DisY2 = 0.02,
                DisZ2 = 0.01,
                Temp1 = 68.5,
                Temp2 = 69.4,
                Temp3 = 68.0,
                Temp4 = 68.9,
                Temp5 = 41.6,
                Temp6 = 41.1,
                Temp7 = 40.2,
                Temp8 = 39.0,
                AmbientHumidity = 62.2,
                AmbientTemperature = 24.9,
                UabIncoming = 380.3,
                UbcIncoming = 380.0,
                UcaIncoming = 379.9,
                UavgIncoming = 380.1,
                IaIncoming = 22.1,
                IbIncoming = 22.0,
                IcIncoming = 22.0,
                IavgIncoming = 22.0,
                PIncoming = 11.0,
                FrequencyIncoming = 50
            },
            new LegacyMotorRealtimeEnvelopeContract
            {
                SampleTime = now.AddSeconds(2),
                DeviceId = "legacy-app-query-seed-01",
                ProductKind = rated.ProductKind,
                VoltageAverage = 380.4,
                CurrentAverage = 21.7,
                Power = 10.6,
                Frequency = 50,
                Speed = 1473,
                Torque = 68.5,
                IsRecordPoint = true,
                Uab = 381.0,
                Ubc = 380.2,
                Uca = 380.0,
                Uavg = 380.4,
                Ia = 21.4,
                Ib = 21.9,
                Ic = 21.8,
                Iavg = 21.7,
                CosPhi = 0.86,
                DeltaI = 0.5,
                AccX1 = 0.13,
                AccY1 = 0.08,
                AccZ1 = 0.05,
                VelX1 = 1.2,
                VelY1 = 1.2,
                VelZ1 = 1.0,
                DisX1 = 0.02,
                DisY1 = 0.03,
                DisZ1 = 0.01,
                AccX2 = 0.11,
                AccY2 = 0.09,
                AccZ2 = 0.04,
                VelX2 = 1.1,
                VelY2 = 0.9,
                VelZ2 = 0.8,
                DisX2 = 0.03,
                DisY2 = 0.02,
                DisZ2 = 0.01,
                Temp1 = 68.9,
                Temp2 = 69.8,
                Temp3 = 68.4,
                Temp4 = 69.1,
                Temp5 = 41.8,
                Temp6 = 41.4,
                Temp7 = 40.4,
                Temp8 = 39.1,
                AmbientHumidity = 62.0,
                AmbientTemperature = 25.0,
                UabIncoming = 381.2,
                UbcIncoming = 380.5,
                UcaIncoming = 380.1,
                UavgIncoming = 380.6,
                IaIncoming = 22.0,
                IbIncoming = 22.2,
                IcIncoming = 22.1,
                IavgIncoming = 22.1,
                PIncoming = 11.1,
                FrequencyIncoming = 50,
                LeaveFactoryModeVibrationCurveImage = "curve://leave-factory/vb/1",
                TempRiseModeVibrationCurveImage = "curve://temp-rise/vb/1"
            }
        };

        return new TestRecordQuerySeedContract
        {
            RatedParams = rated,
            LegacySamples = legacySamples,
            Samples = legacySamples.Select(sample => sample.CoreSample).ToArray(),
            NoLoadRConverseType = 0
        };
    }
}
